### ISSUE TITLE
Where are the adapters?

### ISSUE THREAD

**Issue by ghostsquad** [logur/logur#78]
The README mentioned that you have pre-built adapters for other logging frameworks, but I don't see where they are. I found this from here:

https://github.com/sagikazarmark/modern-go-application

and in particular I see this import:

```
logrusadapter "logur.dev/adapter/logrus"
```

https://github.com/sagikazarmark/modern-go-application/blob/master/internal/platform/log/logger.go

But I don't see an adapter subfolder here. Help!

**Comment by ghostsquad** [comment]
Oh, I didn't know they were sibling repositories. That's a little confusing...

**Comment by sagikazarmark** [comment]
I've spent a considerable amount of time finding a solution for implementing adapters in a way that doesn't require people to download a whole bunch of dependencies that they wouldn't use.

This may not be the best solution (neither from a user nor a maintainer point of view), but it works.

I should probably clarify it more in the README.

**Comment by ghostsquad** [comment]
A readme update would be great! Thanks

**Comment by sagikazarmark** [comment]
@ghostsquad WDYT?


https://github.com/logur/logur/commit/661b6fdfd1cd4891e57686d7d3d831288d656034

**Comment by ghostsquad** [comment]
Lgtm! Thanks
