### ISSUE TITLE
apex/log adapter

### ISSUE THREAD

**Issue by davidalpert** [logur/logur#83]
I have created a logur adapter for the `apex/log` logging library using the adapter template:
- https://github.com/davidalpert/adapter-apex

Would this be of interest for folding into the logur family of adapters?

**Comment by sagikazarmark** [comment]
Hey @davidalpert 

Sure, why not? Do you want to move the repo over to the organization? Or do you want me to place a link to your adapter?

**Comment by davidalpert** [comment]
we can move it over into the organization. I'm using it in a project and it's holding up so far. happy to share it.

what are next steps to do that?

**Comment by davidalpert** [comment]
tried transferring but 
```
You don’t have the permission to create public repositories on logur
```
which makes sense.

let me know the next steps and I'm happy to help with the transfer.

**Comment by sagikazarmark** [comment]
@davidalpert sorry for the radio silence. Can you try to transfer it to me? I can then move it to the org and add you as collaborator.

**Comment by davidalpert** [comment]
```
Repository transfer to sagikazarmark requested
```

**Comment by sagikazarmark** [comment]
Done. Can you send a PR to the vanity import config repo?

**Comment by davidalpert** [comment]
https://github.com/logur/vanity-imports/pull/1
